server:
  port: 7070

spring:
  application:
    name: configserver
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 192.168.152.128:8848
    config:
      server:
        git:
          uri: https://github.com/fangjian0423/blogimages
          search-paths: /

