server:
  port: 18088

spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.152.128:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
